codecov:
  branch: dev
coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0.09
      required:
        target: auto
        threshold: 1
        paths:
          - menuai/components/*/config_flow.py
          - menuai/components/*/device_action.py
          - menuai/components/*/device_condition.py
          - menuai/components/*/device_trigger.py
          - menuai/components/*/diagnostics.py
          - menuai/components/*/group.py
          - menuai/components/*/intent.py
          - menuai/components/*/logbook.py
          - menuai/components/*/media_source.py
          - menuai/components/*/recorder.py
          - menuai/components/*/scene.py
    patch:
      default:
        target: auto
      required:
        target: 100
        threshold: 0
        paths:
          - menuai/components/*/config_flow.py
          - menuai/components/*/device_action.py
          - menuai/components/*/device_condition.py
          - menuai/components/*/device_trigger.py
          - menuai/components/*/diagnostics.py
          - menuai/components/*/group.py
          - menuai/components/*/intent.py
          - menuai/components/*/logbook.py
          - menuai/components/*/media_source.py
          - menuai/components/*/recorder.py
          - menuai/components/*/scene.py
comment: false

# To make partial tests possible,
# we need to carry forward.
flag_management:
  default_rules:
    carryforward: false
  individual_flags:
    - name: full-suite
      paths:
        - ".*"
      carryforward: true
