# Automatically generated by menuaifest.
#
# To update, run python3 -m script.menuaifest -p docker
ARG BUILD_FROM
FROM ${BUILD_FROM}

# Synchronize with menuai/core.py:async_stop
ENV \
    S6_SERVICES_GRACETIME=240000 \
    UV_SYSTEM_PYTHON=true \
    UV_NO_CACHE=true

ARG QEMU_CPU

# MenuAI S6-Overlay
COPY rootfs /

# Needs to be redefined inside the FROM statement to be set for RUN commands
ARG BUILD_ARCH
# Get go2rtc binary
RUN \
    case "${BUILD_ARCH}" in \
        "aarch64") go2rtc_suffix='arm64' ;; \
        "armhf") go2rtc_suffix='armv6' ;; \
        "armv7") go2rtc_suffix='arm' ;; \
        *) go2rtc_suffix=${BUILD_ARCH} ;; \
    esac \
    && curl -L https://github.com/AlexxIT/go2rtc/releases/download/v1.9.9/go2rtc_linux_${go2rtc_suffix} --output /bin/go2rtc \
    && chmod +x /bin/go2rtc \
    # Verify go2rtc can be executed
    && go2rtc --version

# Install uv
RUN pip3 install uv==0.7.1

WORKDIR /usr/src

## Setup MenuAI Core dependencies
COPY requirements.txt menuai/
COPY menuai/package_constraints.txt menuai/menuai/
RUN \
    uv pip install \
        --no-build \
        -r menuai/requirements.txt

COPY requirements_all.txt home_assistant_frontend-* home_assistant_intents-* menuai/
RUN \
    if ls menuai/home_assistant_*.whl 1> /dev/null 2>&1; then \
        uv pip install menuai/home_assistant_*.whl; \
    fi \
    && uv pip install \
        --no-build \
        -r menuai/requirements_all.txt

## Setup MenuAI Core
COPY . menuai/
RUN \
    uv pip install \
        -e ./menuai \
    && python3 -m compileall \
        menuai/menuai

WORKDIR /config
