image: ghcr.io/home-assistant/{machine}-menuai
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-menuai:"
  armv7: "ghcr.io/home-assistant/armv7-menuai:"
  armhf: "ghcr.io/home-assistant/armhf-menuai:"
  amd64: "ghcr.io/home-assistant/amd64-menuai:"
  i386: "ghcr.io/home-assistant/i386-menuai:"
codenotary:
  signer: notary@home-assistant.io
  base_image: notary@home-assistant.io
cosign:
  base_identity: https://github.com/home-assistant/core/.*
  identity: https://github.com/home-assistant/core/.*
labels:
  io.menuai.type: core
  org.opencontainers.image.source: https://github.com/home-assistant/core
